// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 60d22eaf02f84ef40dad37a59f580485c78e6b45cab554d490982100b46f7b28

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "Tailcloakify";

export const themeNames: ThemeName[] = ["Tailcloakify"];

export type KcEnvName =
    | "styles"
    | "scripts"
    | "meta"
    | "TAILCLOAKIFY_ADDITIONAL_SCRIPTS"
    | "TAILCLOAKIFY_ADDITIONAL_STYLES"
    | "TAILCLOAKIFY_ADDITIONAL_META"
    | "TAILCLOAKIFY_BACKGROUND_LOGO_URL"
    | "TAILCLOAKIFY_BACKGROUND_VIDEO_URL"
    | "TAILCLOAKIFY_FAVICON_URL"
    | "TAILCLOAKIFY_FOOTER_IMPRINT_URL"
    | "TAILCLOAKIFY_FOOTER_DATAPROTECTION_URL"
    | "TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT"
    | "TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT_GOOGLE_CAPTCHA";

export const kcEnvNames: KcEnvName[] = [
    "styles",
    "scripts",
    "meta",
    "TAILCLOAKIFY_ADDITIONAL_SCRIPTS",
    "TAILCLOAKIFY_ADDITIONAL_STYLES",
    "TAILCLOAKIFY_ADDITIONAL_META",
    "TAILCLOAKIFY_BACKGROUND_LOGO_URL",
    "TAILCLOAKIFY_BACKGROUND_VIDEO_URL",
    "TAILCLOAKIFY_FAVICON_URL",
    "TAILCLOAKIFY_FOOTER_IMPRINT_URL",
    "TAILCLOAKIFY_FOOTER_DATAPROTECTION_URL",
    "TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT",
    "TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT_GOOGLE_CAPTCHA"
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    styles: "",
    scripts: "",
    meta: "",
    TAILCLOAKIFY_ADDITIONAL_SCRIPTS: "",
    TAILCLOAKIFY_ADDITIONAL_STYLES: "",
    TAILCLOAKIFY_ADDITIONAL_META: "",
    TAILCLOAKIFY_BACKGROUND_LOGO_URL: "",
    TAILCLOAKIFY_BACKGROUND_VIDEO_URL: "",
    TAILCLOAKIFY_FAVICON_URL: "",
    TAILCLOAKIFY_FOOTER_IMPRINT_URL: "",
    TAILCLOAKIFY_FOOTER_DATAPROTECTION_URL: "",
    TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT: "",
    TAILCLOAKIFY_FOOTER_ORESTBIDACOOKIECONSENT_GOOGLE_CAPTCHA: "TRUE"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
